### PR TITLE
Add vertica recovery script

### PR DESCRIPTION
**Pull request by mhoppal**

### CODE REVIEW

**Comment by oneilcin** [comment]
We have to handle special characters in the password (i.e. &) so i think you need double quotes around: 
{{ vertica_admin_password }}

**Comment by tkuhlman** [comment]
Good catch, besides this it looks fine to me.

**Comment by mhoppal** [comment]
Fixed the password and then tested it on failed cluster in CS where I did virsh destroy then virsh start on two of the nodes and then ran this command and it worked.

**Comment by oneilcin** [comment]
looks good to me too - merge when ready

**Pull request merged**
